# Personal Server SSH Configuration
# 1Password item: "Personal Server"
# Fingerprint: (run: ssh-keygen -lf ~/.config/ssh/pubs/personal_server.pub)
Host myserver
  # Simple connection by -> ssh myserver
  HostName 192.168.1.38
  Port 1333
  User wilber
  IdentityFile ~/.config/ssh/pubs/personal_server.pub
  IdentitiesOnly yes
