# Personal Server SSH Configuration
Host myserver
  # Simple connection by -> ssh myserver
  HostName 192.168.1.38
  Port 1333
  User wilber
  IdentityFile ~/.config/ssh/pubs/personal_server.pub
  IdentitiesOnly yes
